/*
SQLyog Ultimate v12.2.4 (64 bit)
MySQL - 5.1.73-log : Database - eoc
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`eoc` /*!40100 DEFAULT CHARACTER SET latin1 */;

USE `eoc`;

/*Table structure for table `EMERGENCY_CONTACT_CATEGORY` */

DROP TABLE IF EXISTS `EMERGENCY_CONTACT_CATEGORY`;

CREATE TABLE `EMERGENCY_CONTACT_CATEGORY` (
  `EME_CAT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CAT_NAME` varchar(50) DEFAULT NULL,
  `DESC` varchar(50) DEFAULT NULL,
  `SEQUENCE` smallint(6) DEFAULT NULL,
  PRIMARY KEY (`EME_CAT_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*Table structure for table `EOC_EMERGENCY_CONTACTS` */

DROP TABLE IF EXISTS `EOC_EMERGENCY_CONTACTS`;

CREATE TABLE `EOC_EMERGENCY_CONTACTS` (
  `EMR_CONTACT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORG_EMPL_ID` smallint(6) DEFAULT NULL,
  `EMR_CAT_ID` smallint(6) DEFAULT NULL,
  `TITLE` varchar(50) DEFAULT NULL,
  `SEAT_NO` varchar(15) DEFAULT NULL,
  `SEAT` varchar(10) DEFAULT NULL,
  `EMP_TYPE` varchar(5) DEFAULT NULL,
  `EXT_CONTACT_NAME` varchar(50) DEFAULT NULL,
  `SEQUENCE` smallint(6) DEFAULT NULL,
  `WORK_PHONE` varchar(12) DEFAULT NULL,
  `MOBILE_PHONE` varchar(12) DEFAULT NULL,
  `OTHER_PHONE` varchar(12) DEFAULT NULL,
  PRIMARY KEY (`EMR_CONTACT_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=51 DEFAULT CHARSET=latin1;

/*Table structure for table `EOC_EMPLOYEE` */

DROP TABLE IF EXISTS `EOC_EMPLOYEE`;

CREATE TABLE `EOC_EMPLOYEE` (
  `EOC_EMPLOYEE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ORG_EMPL_ID` smallint(6) DEFAULT '0',
  `ORG_EMPL_NAME` varchar(250) DEFAULT NULL,
  `ORG_EMPL_FNAME` varchar(50) DEFAULT NULL,
  `ORG_EMPL_LNAME` varchar(50) DEFAULT NULL,
  `ORG_EMPL_MNAME` varchar(30) DEFAULT NULL,
  `ORG_EMPL_EMAIL` varchar(300) DEFAULT NULL,
  `ORG_EMPL_WORK_PHONE` varchar(15) DEFAULT NULL,
  `ORG_EMPL_MOBILE_PHONE` varchar(15) DEFAULT NULL,
  `ORG_EMPL_HR_ID` varchar(20) DEFAULT NULL,
  `ORG_EMPL_BADGE_ID` varchar(20) DEFAULT NULL,
  `ORG_EMPL_TYPE` varchar(20) DEFAULT NULL,
  `ORG_EMPL_IMG_FILE_NAME` varchar(250) DEFAULT NULL,
  `CHANGE_DATE` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `CHANGE_USER` varchar(20) DEFAULT 'hcmsync',
  `CHANGE_TYPE` char(1) DEFAULT 'I',
  `ORG_EMPL_NTWRK_ID` varchar(15) DEFAULT NULL,
  `ORG_EMPL_STATUS` char(1) DEFAULT 'A',
  `ORG_DIV_ID` tinyint(4) NOT NULL DEFAULT '0',
  `ORG_DIV_NAME` varchar(20) NOT NULL,
  `ORG_DIV_LONG_NAME` varchar(100) NOT NULL,
  `ORG_UNIT_ID` smallint(6) NOT NULL DEFAULT '0',
  `ORG_UNIT_NAME` varchar(100) NOT NULL,
  `ORG_UNIT_LONG_NAME` varchar(250) NOT NULL,
  `ORG_LOC_DIV_ID` smallint(6) NOT NULL,
  `ORG_EMPL_DESIGNATION` varchar(100) DEFAULT NULL,
  `ORG_EMPL_REPORT_TO` smallint(6) DEFAULT NULL,
  `ORG_EMPL_ISMGR` char(1) NOT NULL,
  `ORG_MGR_ID_TREE` varchar(200) NOT NULL DEFAULT '',
  PRIMARY KEY (`EOC_EMPLOYEE_ID`),
  KEY `idx_org_empl_id` (`ORG_EMPL_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=3104 DEFAULT CHARSET=latin1;

/*Table structure for table `EOC_EMPLOYEE_EVENT` */

DROP TABLE IF EXISTS `EOC_EMPLOYEE_EVENT`;

CREATE TABLE `EOC_EMPLOYEE_EVENT` (
  `EOC_EVENT_STATUS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EOC_ENT_ID` int(11) NOT NULL,
  `EOC_EVENT_EMP_STATUS` varchar(3) DEFAULT NULL,
  `EOC_EMPLOYEE_ID` int(11) NOT NULL DEFAULT '0',
  `ORG_EMPL_ID` smallint(6) DEFAULT '0',
  `ORG_EMPL_NAME` varchar(250) DEFAULT NULL,
  `ORG_EMPL_FNAME` varchar(50) DEFAULT NULL,
  `ORG_EMPL_LNAME` varchar(50) DEFAULT NULL,
  `ORG_EMPL_MNAME` varchar(30) DEFAULT NULL,
  `ORG_EMPL_EMAIL` varchar(300) DEFAULT NULL,
  `ORG_EMPL_WORK_PHONE` varchar(15) DEFAULT NULL,
  `ORG_EMPL_MOBILE_PHONE` varchar(15) DEFAULT NULL,
  `ORG_EMPL_HR_ID` varchar(20) DEFAULT NULL,
  `ORG_EMPL_BADGE_ID` varchar(20) DEFAULT NULL,
  `ORG_EMPL_TYPE` varchar(20) DEFAULT NULL,
  `ORG_EMPL_IMG_FILE_NAME` varchar(250) DEFAULT NULL,
  `CHANGE_DATE` timestamp NULL DEFAULT '0000-00-00 00:00:00',
  `CHANGE_USER` varchar(20) DEFAULT 'hcmsync',
  `CHANGE_TYPE` char(1) DEFAULT 'I',
  `ORG_EMPL_NTWRK_ID` varchar(15) DEFAULT NULL,
  `ORG_EMPL_STATUS` char(1) DEFAULT 'A',
  `ORG_DIV_ID` tinyint(4) NOT NULL DEFAULT '0',
  `ORG_DIV_NAME` varchar(20) NOT NULL,
  `ORG_DIV_LONG_NAME` varchar(100) NOT NULL,
  `ORG_UNIT_ID` smallint(6) NOT NULL DEFAULT '0',
  `ORG_UNIT_NAME` varchar(100) NOT NULL,
  `ORG_UNIT_LONG_NAME` varchar(250) NOT NULL,
  `ORG_LOC_DIV_ID` smallint(6) NOT NULL,
  `ORG_EMPL_DESIGNATION` varchar(100) DEFAULT NULL,
  `ORG_EMPL_REPORT_TO` smallint(6) DEFAULT NULL,
  `ORG_EMPL_ISMGR` char(1) NOT NULL,
  `ORG_MGR_ID_TREE` varchar(200) NOT NULL DEFAULT '',
  `EVENT_ACTIVE_IND` char(1) DEFAULT NULL,
  PRIMARY KEY (`EOC_EVENT_STATUS_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=27249 DEFAULT CHARSET=latin1;

/*Table structure for table `EOC_EMPLOYEE_EVENT_HISTORY` */

DROP TABLE IF EXISTS `EOC_EMPLOYEE_EVENT_HISTORY`;

CREATE TABLE `EOC_EMPLOYEE_EVENT_HISTORY` (
  `EVENT_HISTORY_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EOC_ENT_ID` bigint(20) DEFAULT NULL,
  `EOC_EVENT_EMP_STATUS` varchar(3) DEFAULT NULL,
  `ORG_EMPL_ID` smallint(6) DEFAULT NULL,
  `GRP_MGR_EMPL_ID` smallint(6) DEFAULT NULL,
  `CHANGE_USER` varchar(20) DEFAULT NULL,
  `CHANGE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`EVENT_HISTORY_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=3186 DEFAULT CHARSET=latin1;

/*Table structure for table `EOC_EVENT` */

DROP TABLE IF EXISTS `EOC_EVENT`;

CREATE TABLE `EOC_EVENT` (
  `EOC_ENT_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EOC_EVNT_TYPE` varchar(20) NOT NULL,
  `EOC_EVNT_DESC` varchar(100) DEFAULT NULL,
  `EOC_EVNT_DATE` date NOT NULL,
  `EOC_EVNT_START_TIME` date NOT NULL,
  `EOC_EVNT_END_TIME` date DEFAULT NULL,
  `CHANGE_DATE` date NOT NULL,
  `CHANGE_USER` varchar(20) NOT NULL,
  `CHANGE_TYPE` char(1) NOT NULL,
  `SITE` varchar(30) DEFAULT NULL,
  `SITE_MGR_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`EOC_ENT_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=17 DEFAULT CHARSET=latin1;

/*Table structure for table `EOC_EVENT_DETAILS` */

DROP TABLE IF EXISTS `EOC_EVENT_DETAILS`;

CREATE TABLE `EOC_EVENT_DETAILS` (
  `EOC_EVNT_DTL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EOC_EMPL_ID` decimal(16,0) NOT NULL,
  `EOC_EMPL_MGR_ID` decimal(16,0) NOT NULL,
  `EOC_EVNT_EMPL_STATUS` char(1) DEFAULT NULL,
  `EOC_EVNT_SAVE_ID` char(1) DEFAULT NULL,
  `EOC_EVNT_EMPL_STAT_DESC` varchar(250) DEFAULT NULL,
  `CHANGE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CHANGE_USER` varchar(20) NOT NULL,
  `CHANGE_TYPE` char(1) NOT NULL,
  `EOC_ENT_ID` decimal(16,0) DEFAULT NULL,
  `ORG_DIV_EMPL_ID` decimal(16,0) DEFAULT NULL,
  `EOC_EMP_NOTES` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`EOC_EVNT_DTL_ID`),
  KEY `EOC_EVNT_DTL_I` (`EOC_ENT_ID`),
  KEY `ORG_DIV_EMPL_EVNT_I` (`ORG_DIV_EMPL_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=3440 DEFAULT CHARSET=latin1;

/*Table structure for table `EOC_EVENT_DETAILS_HISTORY` */

DROP TABLE IF EXISTS `EOC_EVENT_DETAILS_HISTORY`;

CREATE TABLE `EOC_EVENT_DETAILS_HISTORY` (
  `EOC_EVNT_DTL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EOC_EMPL_ID` decimal(16,0) NOT NULL,
  `EOC_EMPL_MGR_ID` decimal(16,0) NOT NULL,
  `EOC_EVNT_EMPL_STATUS` char(1) DEFAULT NULL,
  `EOC_EVNT_EMPL_STAT_DESC` varchar(250) DEFAULT NULL,
  `CHANGE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CHANGE_USER` varchar(20) NOT NULL,
  `CHANGE_TYPE` char(1) NOT NULL,
  `EOC_ENT_ID` decimal(16,0) DEFAULT NULL,
  `EOC_EVNT_DTL_PARENT_ID` bigint(20) DEFAULT NULL,
  `ORG_DIV_EMPL_ID` decimal(16,0) DEFAULT NULL,
  `EOC_EMP_NOTES` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`EOC_EVNT_DTL_ID`),
  KEY `EOC_EVNT_DTL_I` (`EOC_ENT_ID`),
  KEY `ORG_DIV_EMPL_EVNT_I` (`ORG_DIV_EMPL_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=824 DEFAULT CHARSET=latin1;

/*Table structure for table `EOC_EVENT_STATUS` */

DROP TABLE IF EXISTS `EOC_EVENT_STATUS`;

CREATE TABLE `EOC_EVENT_STATUS` (
  `EOC_EVENT_STATUS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EOC_ENT_ID` bigint(20) DEFAULT NULL,
  `LOV_EVENT_STATUS_ID` smallint(6) DEFAULT NULL,
  `CHANGE_USER` varchar(20) DEFAULT NULL COMMENT 'EMPLOYEE ID',
  `CHANGE_TIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STATUS_MSG` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`EOC_EVENT_STATUS_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=22 DEFAULT CHARSET=latin1;

/*Table structure for table `EOC_USER_LOGINS` */

DROP TABLE IF EXISTS `EOC_USER_LOGINS`;

CREATE TABLE `EOC_USER_LOGINS` (
  `LOGIN_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ORG_EMPL_NTWRK_ID` varchar(10) DEFAULT NULL,
  `ORG_EMPL_ID` bigint(20) DEFAULT NULL,
  `CHANGE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `EOC_ENT_ID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`LOGIN_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=2648 DEFAULT CHARSET=latin1;

/*Table structure for table `LOV_EVENT_STATUS` */

DROP TABLE IF EXISTS `LOV_EVENT_STATUS`;

CREATE TABLE `LOV_EVENT_STATUS` (
  `LOV_EVENT_STATUS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EVENT_STATUS` varchar(30) DEFAULT NULL,
  `EVENT_MSG` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`LOV_EVENT_STATUS_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

/*Table structure for table `M2E_REPORT_DELTA` */

DROP TABLE IF EXISTS `M2E_REPORT_DELTA`;

CREATE TABLE `M2E_REPORT_DELTA` (
  `EMPLID` varchar(45) NOT NULL,
  `MGRID` varchar(45) NOT NULL,
  `EMPL_NAME` varchar(100) NOT NULL,
  KEY `REPORT_INDX` (`EMPLID`,`MGRID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `ORGANIZATION` */

DROP TABLE IF EXISTS `ORGANIZATION`;

CREATE TABLE `ORGANIZATION` (
  `ORG_ID` decimal(16,0) NOT NULL,
  `ORG_NAME` varchar(250) NOT NULL,
  `CHANGE_DATE` date NOT NULL,
  `CHANGE_USER` varchar(20) NOT NULL,
  `CHANGE_TYPE` char(1) NOT NULL,
  PRIMARY KEY (`ORG_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `ORG_DIVISION` */

DROP TABLE IF EXISTS `ORG_DIVISION`;

CREATE TABLE `ORG_DIVISION` (
  `ORG_DIV_ID` tinyint(4) NOT NULL AUTO_INCREMENT,
  `ORG_DIV_NAME` varchar(20) NOT NULL,
  `CHANGE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ORG_DIV_LONG_NAME` varchar(100) NOT NULL,
  `CHANGE_USER` varchar(20) NOT NULL DEFAULT 'hcmsync',
  `CHANGE_TYPE` char(1) NOT NULL DEFAULT 'I',
  PRIMARY KEY (`ORG_DIV_ID`),
  UNIQUE KEY `ORG_DIV_NAME_UNIQUE` (`ORG_DIV_NAME`)
) ENGINE=MyISAM AUTO_INCREMENT=38 DEFAULT CHARSET=latin1;

/*Table structure for table `ORG_DIV_EMPL` */

DROP TABLE IF EXISTS `ORG_DIV_EMPL`;

CREATE TABLE `ORG_DIV_EMPL` (
  `ORG_DIV_EMPL_ID` smallint(6) NOT NULL AUTO_INCREMENT,
  `ORG_LOC_DIV_ID` smallint(6) NOT NULL,
  `ORG_EMPL_ID` smallint(6) NOT NULL,
  `ORG_EMPL_DESIGNATION` varchar(100) DEFAULT NULL,
  `ORG_EMPL_REPORT_TO` smallint(6) DEFAULT NULL,
  `ORG_EMPL_ISMGR` char(1) NOT NULL,
  `ORG_MGR_ID_TREE` varchar(200) NOT NULL DEFAULT '',
  PRIMARY KEY (`ORG_DIV_EMPL_ID`),
  UNIQUE KEY `ORG_EMPL_ID_UNIQUE` (`ORG_EMPL_ID`),
  KEY `ORG_DIV_EMPL_I` (`ORG_LOC_DIV_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=3167 DEFAULT CHARSET=latin1;

/*Table structure for table `ORG_EMPLOYEES` */

DROP TABLE IF EXISTS `ORG_EMPLOYEES`;

CREATE TABLE `ORG_EMPLOYEES` (
  `ORG_EMPL_ID` smallint(6) NOT NULL AUTO_INCREMENT,
  `ORG_EMPL_NAME` varchar(250) NOT NULL,
  `ORG_EMPL_FNAME` varchar(50) NOT NULL,
  `ORG_EMPL_LNAME` varchar(50) NOT NULL,
  `ORG_EMPL_MNAME` varchar(30) DEFAULT NULL,
  `ORG_EMPL_EMAIL` varchar(300) DEFAULT NULL,
  `ORG_EMPL_WORK_PHONE` varchar(15) DEFAULT NULL,
  `ORG_EMPL_MOBILE_PHONE` varchar(15) DEFAULT NULL,
  `ORG_EMPL_HR_ID` varchar(20) NOT NULL,
  `ORG_EMPL_BADGE_ID` varchar(20) DEFAULT NULL,
  `ORG_EMPL_TYPE` varchar(20) DEFAULT NULL,
  `ORG_EMPL_IMG_FILE_NAME` varchar(250) DEFAULT NULL,
  `CHANGE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CHANGE_USER` varchar(20) NOT NULL DEFAULT 'hcmsync',
  `CHANGE_TYPE` char(1) NOT NULL DEFAULT 'I',
  `ORG_EMPL_NTWRK_ID` varchar(15) DEFAULT NULL,
  `ORG_EMPL_STATUS` char(1) NOT NULL DEFAULT 'A',
  PRIMARY KEY (`ORG_EMPL_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=3107 DEFAULT CHARSET=latin1;

/*Table structure for table `ORG_LOCATION` */

DROP TABLE IF EXISTS `ORG_LOCATION`;

CREATE TABLE `ORG_LOCATION` (
  `ORG_LOC_ID` decimal(16,0) NOT NULL,
  `ORG_LOC_NAME` varchar(100) NOT NULL,
  `ORG_LOC_ADDR1` varchar(250) NOT NULL,
  `ORG_LOC_ADDR2` varchar(250) DEFAULT NULL,
  `ORG_LOC_CITY` varchar(100) NOT NULL,
  `ORG_LOC_STATE` varchar(50) NOT NULL,
  `ORG_LOC_ZIP` varchar(15) NOT NULL,
  `ORG_LOC_TYPE` varchar(50) NOT NULL,
  `CHANGE_DATE` date DEFAULT NULL,
  `CHANGE_USER` varchar(20) DEFAULT NULL,
  `CHANGE_TYPE` char(1) DEFAULT NULL,
  `ORG_ID` decimal(16,0) DEFAULT NULL,
  PRIMARY KEY (`ORG_LOC_ID`),
  KEY `ORG_LOC_I` (`ORG_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `ORG_LOC_DIV` */

DROP TABLE IF EXISTS `ORG_LOC_DIV`;

CREATE TABLE `ORG_LOC_DIV` (
  `ORG_LOC_DIV_ID` smallint(6) NOT NULL AUTO_INCREMENT,
  `ORG_LOC_ID` smallint(6) NOT NULL DEFAULT '1',
  `ORG_DIV_ID` smallint(6) NOT NULL,
  `CHANGE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CHANGE_USER` varchar(20) NOT NULL DEFAULT 'hcmsync',
  `CHANGE_TYPE` char(1) NOT NULL DEFAULT 'I',
  `ORG_UNIT_ID` smallint(6) NOT NULL,
  PRIMARY KEY (`ORG_LOC_DIV_ID`),
  KEY `ORG_DIV_LOC_I` (`ORG_DIV_ID`),
  KEY `ORG_LOC_DIV_I` (`ORG_LOC_ID`),
  KEY `ORG_LOC_DIV_UNIT` (`ORG_UNIT_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=610 DEFAULT CHARSET=latin1;

/*Table structure for table `ORG_ROLE` */

DROP TABLE IF EXISTS `ORG_ROLE`;

CREATE TABLE `ORG_ROLE` (
  `ORG_ROLE_ID` decimal(16,0) NOT NULL,
  `ORG_ROLE_NAME` varchar(20) NOT NULL,
  `ORG_ROLE_DESC` varchar(100) DEFAULT NULL,
  `CHANGE_DATE` date NOT NULL,
  `CHANGE_USER` varchar(20) DEFAULT NULL,
  `CHANGE_TYPE` char(1) NOT NULL,
  PRIMARY KEY (`ORG_ROLE_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `ORG_ROLE_EVNT` */

DROP TABLE IF EXISTS `ORG_ROLE_EVNT`;

CREATE TABLE `ORG_ROLE_EVNT` (
  `ORG_ROLE_EVNT_ID` decimal(16,0) NOT NULL,
  `ORG_ROLE_ID` decimal(16,0) DEFAULT NULL,
  `ORG_DIV_EMPL_ID` decimal(16,0) DEFAULT NULL,
  `CHANGE_DATE` date NOT NULL,
  `CHANGE_USER` varchar(20) NOT NULL,
  `CHANGE_TYPE` char(1) NOT NULL,
  `ORG_EMPL_ID` decimal(16,0) DEFAULT NULL,
  PRIMARY KEY (`ORG_ROLE_EVNT_ID`),
  KEY `ORG_DIV_ROLE_EVNT` (`ORG_DIV_EMPL_ID`),
  KEY `ORG_ROLE_EVNT_EMPL` (`ORG_ROLE_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*Table structure for table `ORG_UNIT` */

DROP TABLE IF EXISTS `ORG_UNIT`;

CREATE TABLE `ORG_UNIT` (
  `ORG_UNIT_ID` smallint(6) NOT NULL AUTO_INCREMENT,
  `ORG_UNIT_NAME` varchar(100) NOT NULL,
  `ORG_UNIT_LONG_NAME` varchar(250) NOT NULL,
  `CHANGE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `CHANGE_USER` varchar(20) NOT NULL DEFAULT 'hcmsync',
  `CHANGE_TYPE` char(1) NOT NULL DEFAULT 'I',
  `ORG_DIV_ID` smallint(6) NOT NULL,
  `ORG_UNIT_HR_ID` varchar(10) NOT NULL,
  PRIMARY KEY (`ORG_UNIT_ID`),
  UNIQUE KEY `ORG_UNIT_HR_ID_UNIQUE` (`ORG_UNIT_HR_ID`),
  KEY `ORG_DIV_UNIT` (`ORG_DIV_ID`)
) ENGINE=MyISAM AUTO_INCREMENT=610 DEFAULT CHARSET=latin1;

/*Table structure for table `WF_METRIC_DETAILS` */

DROP TABLE IF EXISTS `WF_METRIC_DETAILS`;

CREATE TABLE `WF_METRIC_DETAILS` (
  `WF_METRIC_DTL_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `EOC_EMPL_ID` decimal(16,0) NOT NULL,
  `EOC_EMPL_MGR_ID` decimal(16,0) NOT NULL,
  `CHANGE_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CHANGE_USER` varchar(20) NOT NULL,
  `CHANGE_TYPE` char(1) NOT NULL,
  `ORG_DIV_EMPL_ID` decimal(16,0) DEFAULT NULL,
  `WF_SUB_CAT` varchar(250) DEFAULT NULL,
  `WF_CAT` varchar(250) DEFAULT NULL,
  `WF_PERCENT` decimal(16,0) DEFAULT NULL,
  PRIMARY KEY (`WF_METRIC_DTL_ID`),
  KEY `ORG_DIV_EMPL_EVNT_I` (`ORG_DIV_EMPL_ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
